version: '3.7'

services:
  app:
    build: .
    expose:
      - "5000"
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginx.conf.d:/etc/nginx/conf.d
      - ./app/cert.pem:/etc/nginx/ssl/cert.pem
      - ./app/key.pem:/etc/nginx/ssl/key.pem
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
